const countryMap = {
    "US": "United States",
    "GB": "United Kingdom",
    "FR": "France",
    "DE": "Germany",
    "IT": "Italy",
    "JP": "Japan",
    "AU": "Australia",
    "CA": "Canada",
    "IN": "India",
    "DK": "Denmark",
    "AT": "Austria",
    "SE": "Sweden",
    "NO": "Norway",
    "ES": "Spain",
    "NZ": "New Zealand",
    "IE": "Ireland",
    "HK": "Hong Kong",
    "BR": "Brazil",
    "MX": "Mexico",
    "KR": "South Korea",
    "CN": "China",
    "SU": "Soviet Union",
    "IR": "Iran",
    "PL": "Poland",
    "CZ": "Czech Republic",
    "AR": "Argentina",
    "LV": "Latvia",
    "MK": "North Macedonia",
    "CR": "Costa Rica",
    "HN": "Honduras",
    "DO": "Dominican Republic",
    "LU": "Luxembourg",
    "PH": "Philippines",
    "PT": "Portugal",
    "ZA": "South Africa",
}

export default countryMap;